"""Result file writers for Phase E.

Functions:
  write_per_folder_quality_summaries - one fit_quality_summary.csv per fit
                                       folder (mirror Step 15's behaviour).
  write_low_retention_log            - low_retention_warnings.txt (also
                                       removes a stale file if log is empty).
  print_retention_stats              - per-fixation diagnostic table.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd


def write_per_folder_quality_summaries(
    mask_summary_df: pd.DataFrame,
    data_dirs: Iterable[Path],
    *,
    drop_cols: tuple = ("session_root", "fit_folder", "fit_set_key"),
    out_name: str = "fit_quality_summary.csv",
) -> int:
    """Write one CSV per fit folder.  Returns number of files written."""
    n = 0
    if mask_summary_df.empty:
        return n
    data_dirs = list(data_dirs)
    for (session_root, fit_folder), grp in mask_summary_df.groupby(
        ["session_root", "fit_folder"]
    ):
        session_dir = next((d for d in data_dirs if d.name == session_root), None)
        if session_dir is None:
            continue
        out_path = session_dir / Path(fit_folder) / out_name
        grp.drop(columns=list(drop_cols), errors="ignore").to_csv(
            out_path, index=False)
        n += 1
    return n


def write_low_retention_log(
    records: list,
    path: Path | str,
    *,
    header: str = ("# Fit sets with <1% pixel retention -- re-fit with higher "
                   "b_val\n# Generated by pipeline.batch.process_all_fit_sets\n\n"),
    verbose: bool = True,
) -> int:
    """Write the low-retention warnings text file.

    `records`: list of (sdt_filename, fit_folder, b_val, pct_final) tuples.
    Removes a stale file at `path` if records is empty.  Returns the number
    of records written.
    """
    path = Path(path)
    if not records:
        if path.exists():
            path.unlink()
        if verbose:
            print("  No low-retention fit sets (all >= 1%).")
        return 0
    if verbose:
        print(f"\n[WARNING] {len(records)} fit set(s) with <1% pixels accepted"
              f" -- written to {path}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header)
        for fn, folder, b, pct in records:
            msg = f"pct={pct:.2f}%  b={b}  folder={folder}  file={fn}"
            if verbose:
                print(f"  [LOW RETENTION] {msg}")
            fh.write(msg + "\n")
    return len(records)


def print_retention_stats(mask_summary_df: pd.DataFrame) -> None:
    """Print per-fixation pixel retention diagnostics (matches Step 15 tail)."""
    if mask_summary_df.empty or "pct_final" not in mask_summary_df.columns:
        return
    print("\nPixel retention by fixation_type (%):")
    print(mask_summary_df.groupby("fixation_type")["pct_final"]
          .agg(["mean", "median", "min", "max"]).round(1).to_string())
    print("\nPer-criterion counts (mean over files):")
    crit_cols = ["n_photon_ok", "n_chi2_ok", "n_amp_ok", "n_tau_ok", "n_final"]
    print(mask_summary_df.groupby("fixation_type")[crit_cols]
          .mean().round(0).to_string())
