"""Load + normalize config/default.yaml into the dicts the library expects.

The YAML file uses lists where the library expects tuples and uses string
keys (like 'default') where the library expects None.  load_config() does
this normalization so notebook code can simply do:

    from src.config import load_config
    cfg = load_config()
    mask, brk = compute_fit_mask(
        fd, fixation_type, b_val,
        min_photons_by_ncomp=cfg['min_photons_by_ncomp'],
        chi2_lo=cfg['chi2_lo'], chi2_hi=cfg['chi2_hi'],
        tau_bounds=cfg['tau_bounds'],
        tau_mean_bounds=cfg['tau_mean_bounds'],
        taumean_cfg=cfg['taumean_cfg'],
    )
"""

from __future__ import annotations

from pathlib import Path

import yaml


_CONFIG_DIR          = Path(__file__).resolve().parent.parent / "config"
DEFAULT_CONFIG_PATH  = _CONFIG_DIR / "default.yaml"
DATA_DIRS_PATH       = _CONFIG_DIR / "data_dirs.yaml"


def load_config(path: Path | str | None = None) -> dict:
    """Load config/default.yaml and normalize types.

    Conversions applied:
      min_photons_by_ncomp:  int / 'default' keys -> int / None
      tau_bounds[ft][param]: [lo, hi] list        -> (lo, hi) tuple
      tau_mean_bounds[ft]:   [lo, hi] list        -> (lo, hi) tuple (or None)
      taumean_cfg[ft]:       [[a, t], ...]        -> (('a', 'tau'), ...)
      ratio_cfg[ft]:         [num, den]           -> ('num', 'den')
    """
    p = Path(path) if path is not None else DEFAULT_CONFIG_PATH
    with open(p, encoding="utf-8") as fh:
        raw = yaml.safe_load(fh)

    out = dict(raw)   # shallow copy

    # min_photons_by_ncomp: 'default' -> None, '1'/'2'/'3' -> int
    mph = {}
    for k, v in raw.get("min_photons_by_ncomp", {}).items():
        if k == "default":
            mph[None] = v
        else:
            mph[int(k)] = v
    out["min_photons_by_ncomp"] = mph

    # tau_bounds: lists -> tuples
    tb = {}
    for ft, params in (raw.get("tau_bounds") or {}).items():
        tb[ft] = {p_: tuple(rng) for p_, rng in params.items()}
    out["tau_bounds"] = tb

    # tau_mean_bounds: list -> tuple, preserve None
    tmb = {}
    for ft, rng in (raw.get("tau_mean_bounds") or {}).items():
        tmb[ft] = tuple(rng) if rng is not None else None
    out["tau_mean_bounds"] = tmb

    # taumean_cfg: nested lists -> nested tuples
    tcfg = {}
    for ft, pairs in (raw.get("taumean_cfg") or {}).items():
        tcfg[ft] = tuple(tuple(pair) for pair in pairs)
    out["taumean_cfg"] = tcfg

    # ratio_cfg: list -> tuple
    rcfg = {}
    for ft, pair in (raw.get("ratio_cfg") or {}).items():
        rcfg[ft] = tuple(pair)
    out["ratio_cfg"] = rcfg

    return out


def save_data_dirs(
    win_dirs: list,
    lin_dirs: list,
    *,
    path: Path | str | None = None,
) -> Path:
    """Write data_dirs to config/data_dirs.yaml (called by Phase A).

    The file is overwritten in place each run.  Phase A is the single
    authoritative source for which .sdt session directories belong to the
    pipeline; downstream phases read this file via get_data_dirs().

    Args:
        win_dirs: list of Windows session-root paths (strings or Paths).
        lin_dirs: list of Linux  session-root paths.
        path:     defaults to config/data_dirs.yaml.

    Returns the path written.
    """
    out = Path(path) if path is not None else DATA_DIRS_PATH
    payload = {
        "data_dirs": {
            "win": [str(p) for p in win_dirs],
            "lin": [str(p) for p in lin_dirs],
        },
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(
            "# Auto-generated by Phase A (notebooks/20260507_KPC_explore).\n"
            "# Do not hand-edit -- changes are overwritten on the next Phase A run.\n"
            "# Edit the WIN_DATA_DIRS / LIN_DATA_DIRS lists at the top of Phase A,\n"
            "# then re-run Phase A.  Downstream phases read this file via\n"
            "# src.config.get_data_dirs().\n\n"
        )
        yaml.safe_dump(payload, fh, sort_keys=False)
    return out


def get_data_dirs(
    config: dict | None = None,
    *,
    require_exist: bool = True,
) -> list[Path]:
    """Return raw .sdt session directories as Path objects.

    Precedence:
      1. config/data_dirs.yaml  (written by Phase A; authoritative)
      2. config/default.yaml's data_dirs section (fallback for backwards
         compatibility before Phase A has been run on this checkout)

    Returns the union of `win:` and `lin:` lists, filtered to paths that
    exist on disk, deduplicated and order-preserving.

    Args:
        config:        pre-loaded default.yaml dict; if None, both files are
                       loaded fresh.
        require_exist: raise FileNotFoundError when nothing exists.
    """
    # 1. Prefer data_dirs.yaml when present
    raw: dict = {}
    if DATA_DIRS_PATH.exists():
        with open(DATA_DIRS_PATH, encoding="utf-8") as fh:
            raw = (yaml.safe_load(fh) or {}).get("data_dirs", {}) or {}
    # 2. Fall back to default.yaml's data_dirs section
    if not raw:
        cfg = config if config is not None else load_config()
        raw = cfg.get("data_dirs", {}) or {}
    seen: set[str] = set()
    out:  list[Path] = []
    for os_key in ("win", "lin"):
        for d in raw.get(os_key, []) or []:
            p = Path(d)
            key = str(p)
            if key in seen:
                continue
            seen.add(key)
            if not require_exist or p.exists():
                out.append(p)
    if require_exist and not out:
        raise FileNotFoundError(
            f"None of the data_dirs in config exist on this machine.  "
            f"Listed: {list(seen)}"
        )
    return out
